version: 0.0
os: linux

# Make sure that "destination" is not same for two different Code Deploy Groups/Deployments.
files:
  - source: /
    destination: /home/ubuntu/server2

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 30
      runas: ubuntu
  ApplicationStop:
    - location: stop.sh
      timeout: 20
      runas: ubuntu
  ApplicationStart:
    - location: start.sh
      timeout: 20
      runas: ubuntu
  ValidateService:
    - location: validate.sh
      timeout: 20
      runas: ubuntu
